// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: v1/random.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request is empty; we just subscribe.
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_v1_random_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_random_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_v1_random_proto_rawDescGZIP(), []int{0}
}

// The stream item.
type Number struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Number) Reset() {
	*x = Number{}
	mi := &file_v1_random_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Number) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Number) ProtoMessage() {}

func (x *Number) ProtoReflect() protoreflect.Message {
	mi := &file_v1_random_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Number.ProtoReflect.Descriptor instead.
func (*Number) Descriptor() ([]byte, []int) {
	return file_v1_random_proto_rawDescGZIP(), []int{1}
}

func (x *Number) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_v1_random_proto protoreflect.FileDescriptor

const file_v1_random_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/random.proto\x12\trandom.v1\"\x12\n" +
	"\x10SubscribeRequest\"\x1e\n" +
	"\x06Number\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value2T\n" +
	"\rRandomService\x12C\n" +
	"\x0fSubscribeRandom\x12\x1b.random.v1.SubscribeRequest\x1a\x11.random.v1.Number0\x01B\x12Z\x10demoapi/pb/v1;pbb\x06proto3"

var (
	file_v1_random_proto_rawDescOnce sync.Once
	file_v1_random_proto_rawDescData []byte
)

func file_v1_random_proto_rawDescGZIP() []byte {
	file_v1_random_proto_rawDescOnce.Do(func() {
		file_v1_random_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_random_proto_rawDesc), len(file_v1_random_proto_rawDesc)))
	})
	return file_v1_random_proto_rawDescData
}

var file_v1_random_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_random_proto_goTypes = []any{
	(*SubscribeRequest)(nil), // 0: random.v1.SubscribeRequest
	(*Number)(nil),           // 1: random.v1.Number
}
var file_v1_random_proto_depIdxs = []int32{
	0, // 0: random.v1.RandomService.SubscribeRandom:input_type -> random.v1.SubscribeRequest
	1, // 1: random.v1.RandomService.SubscribeRandom:output_type -> random.v1.Number
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_random_proto_init() }
func file_v1_random_proto_init() {
	if File_v1_random_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_random_proto_rawDesc), len(file_v1_random_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_random_proto_goTypes,
		DependencyIndexes: file_v1_random_proto_depIdxs,
		MessageInfos:      file_v1_random_proto_msgTypes,
	}.Build()
	File_v1_random_proto = out.File
	file_v1_random_proto_goTypes = nil
	file_v1_random_proto_depIdxs = nil
}
